const API="https://nova-tv-api.mikimc-business.workers.dev";
const state={token:sessionStorage.getItem("novaTvAdminToken")||"",playlists:[],categories:[],channels:[],reports:[],selected:null};
const $=id=>document.getElementById(id);const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function toast(s){const e=$("toast");e.textContent=s;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2600)}
async function api(path,opt={}){const h=new Headers(opt.headers||{});if(opt.body)h.set("Content-Type","application/json");if(path.startsWith("/api/admin/")){if(!state.token)throw Error("Configura el token");h.set("Authorization","Bearer "+state.token)}const r=await fetch(API+path,{...opt,headers:h});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
async function loadAll(){try{const [p,c,ch]=await Promise.all([api("/api/admin/playlists"),api("/api/admin/categories"),api("/api/admin/channels")]);state.playlists=p;state.categories=c;state.channels=ch;renderOptions();renderChannels();renderPlaylists();renderCategories();$("apiStatus").textContent="● API conectada"}catch(e){toast(e.message);if(!state.token)$("tokenDialog").showModal()}}
function renderOptions(){const po=`<option value="">Todas las listas</option>`+state.playlists.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("");$("playlistFilter").innerHTML=po;$("playlistId").innerHTML=state.playlists.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("");$("categoryFilter").innerHTML=`<option value="">Todas las categorías</option>`+state.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("");$("categoryId").innerHTML=state.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("")}
function filtered(){const q=$("search").value.toLowerCase(),p=$("playlistFilter").value,c=$("categoryFilter").value;return state.channels.filter(x=>(!p||String(x.playlist_id)===p)&&(!c||String(x.category_id)===c)&&(!q||[x.name,x.stream_url,x.category_name,x.playlist_name,x.provider].some(v=>String(v||"").toLowerCase().includes(q))))}
function renderChannels(){const rows=filtered();$("statsText").textContent=`${rows.length} visibles · ${state.channels.length} canales · ${state.playlists.length} listas`;$("channelList").innerHTML=rows.map(c=>`<div class="channel" data-id="${c.id}">${c.logo_url?`<img src="${esc(c.logo_url)}">`:`<div class="logo"></div>`}<div><strong>${esc(c.number||"")} ${esc(c.name)}</strong><small>${esc(c.playlist_name)} · ${esc(c.category_name)}</small><small>${esc(c.stream_url)}</small></div><span class="pill">${c.active?"Activo":"Oculto"}</span></div>`).join("")||"<p>Sin canales</p>";document.querySelectorAll(".channel").forEach(el=>el.onclick=()=>editChannel(Number(el.dataset.id)))}
function editChannel(id){const c=state.channels.find(x=>x.id===id);if(!c)return;state.selected=c;$("channelId").value=c.id;$("playlistId").value=c.playlist_id;$("number").value=c.number||"";$("name").value=c.name||"";$("categoryId").value=c.category_id;$("epgId").value=c.epg_id||"";$("logoUrl").value=c.logo_url||"";$("streamUrl").value=c.stream_url||"";$("backupUrl").value=c.backup_url||"";$("tvgId").value=c.tvg_id||"";$("provider").value=c.provider||"";$("sortOrder").value=c.sort_order||0;$("active").checked=!!c.active}
function clearForm(){state.selected=null;$("channelForm").reset();$("channelId").value="";$("active").checked=true;$("sortOrder").value=state.channels.length+1}
function payload(){return{name:$("name").value.trim(),number:$("number").value.trim()||null,playlist_id:Number($("playlistId").value),category_id:Number($("categoryId").value),epg_id:$("epgId").value.trim()||null,logo_url:$("logoUrl").value.trim()||null,stream_url:$("streamUrl").value.trim(),backup_url:$("backupUrl").value.trim()||null,tvg_id:$("tvgId").value.trim()||null,provider:$("provider").value.trim()||null,sort_order:Number($("sortOrder").value||0),active:$("active").checked}}
$("channelForm").onsubmit=async e=>{e.preventDefault();try{const id=$("channelId").value,p=payload();await api(id?`/api/admin/channels/${id}`:"/api/admin/channels",{method:id?"PUT":"POST",body:JSON.stringify(p)});toast(id?"Canal actualizado":"Canal creado");clearForm();await loadAll()}catch(e){toast(e.message)}};
$("btnDeleteChannel").onclick=async()=>{const id=$("channelId").value;if(!id)return toast("Selecciona un canal");if(!confirm("¿Eliminar este canal?"))return;try{await api(`/api/admin/channels/${id}`,{method:"DELETE"});clearForm();await loadAll()}catch(e){toast(e.message)}};$("btnClear").onclick=clearForm;$("btnNewChannel").onclick=clearForm;[$("search"),$("playlistFilter"),$("categoryFilter")].forEach(e=>e.addEventListener(e.tagName==="INPUT"?"input":"change",renderChannels));
function renderPlaylists(){$("playlistCards").innerHTML=state.playlists.map(p=>`<div class="card"><div class="cardhead"><div><strong>${esc(p.name)}</strong><small>${esc(p.slug)} · ${p.channel_count||0} canales</small></div><div><button onclick="openSimple('playlist',${p.id})">Editar</button> <button class="danger" onclick="deleteSimple('playlist',${p.id})">Eliminar</button></div></div></div>`).join("")}
function renderCategories(){$("categoryCards").innerHTML=state.categories.map(c=>`<div class="card"><div class="cardhead"><div><strong>${esc(c.name)}</strong><small>${esc(c.slug)} · ${c.channel_count||0} canales</small></div><div><button onclick="openSimple('category',${c.id})">Editar</button> <button class="danger" onclick="deleteSimple('category',${c.id})">Eliminar</button></div></div></div>`).join("")}
window.openSimple=(type,id=0)=>{const arr=type==="playlist"?state.playlists:state.categories,o=arr.find(x=>x.id===id);$("simpleType").value=type;$("simpleId").value=id||"";$("simpleTitle").textContent=(id?"Editar ":"Nueva ")+(type==="playlist"?"lista":"categoría");$("simpleName").value=o?.name||"";$("simpleSlug").value=o?.slug||"";$("simpleOrder").value=o?.sort_order||0;$("simpleActive").checked=o?!!o.active:true;$("simpleDialog").showModal()};
window.deleteSimple=async(type,id)=>{if(!confirm("¿Eliminar?"))return;try{await api(`/api/admin/${type==="playlist"?"playlists":"categories"}/${id}`,{method:"DELETE"});await loadAll()}catch(e){toast(e.message)}};
$("simpleForm").onsubmit=async e=>{e.preventDefault();const type=$("simpleType").value,id=$("simpleId").value,path=type==="playlist"?"playlists":"categories",body={name:$("simpleName").value.trim(),slug:$("simpleSlug").value.trim(),sort_order:Number($("simpleOrder").value||0),active:$("simpleActive").checked};try{await api(`/api/admin/${path}${id?`/${id}`:""}`,{method:id?"PUT":"POST",body:JSON.stringify(body)});$("simpleDialog").close();await loadAll()}catch(e){toast(e.message)}};$("btnNewPlaylist").onclick=()=>openSimple("playlist");$("btnNewCategory").onclick=()=>openSimple("category");
async function loadReports(){try{state.reports=await api("/api/admin/reports");const open=state.reports.filter(r=>r.status==="open").length;$("reportBadge").textContent=open?`(${open})`:"";$("reportCards").innerHTML=state.reports.map(r=>`<div class="card"><div class="cardhead"><div><strong>${esc(r.channel_name)}</strong><small>${esc(r.playlist_name)} · ${esc(r.reason)} · ${esc(r.created_at)}</small></div><button onclick="reportStatus(${r.id},'${r.status==='open'?'resolved':'open'}')">${r.status==='open'?'Resolver':'Reabrir'}</button></div></div>`).join("")||"<p>Sin reportes</p>"}catch(e){toast(e.message)}}window.reportStatus=async(id,status)=>{try{await api(`/api/admin/reports/${id}`,{method:"PUT",body:JSON.stringify({status})});await loadReports()}catch(e){toast(e.message)}};$("btnReloadReports").onclick=loadReports;
function parseM3U(txt){const lines=txt.split(/\r?\n/),attrs=/([\w-]+)="([^"]*)"/g,out=[];let meta=null,name="";for(const raw of lines){const line=raw.trim();if(line.startsWith("#EXTINF")){meta={};for(const m of line.matchAll(attrs))meta[m[1]]=m[2];name=line.substring(line.indexOf(",")+1).trim()}else if(meta&&line&&!line.startsWith("#")){out.push({name:name||meta["tvg-name"]||"Canal",number:meta["tvg-chno"]||null,logo_url:meta["tvg-logo"]||null,tvg_id:meta["tvg-id"]||null,provider:meta["provider"]||null,group:meta["group-title"]||"Otros",stream_url:line});meta=null}}return out}
$("m3uFile").onchange=async e=>{const file=e.target.files[0];if(!file)return;let playlistId=Number($("playlistFilter").value);if(!playlistId)playlistId=Number(prompt("ID de la lista destino:",state.playlists[0]?.id||""));if(!playlistId)return;try{const parsed=parseM3U(await file.text());if(!parsed.length)throw Error("No encontré canales");const groups=[...new Set(parsed.map(x=>x.group))];for(const g of groups){if(!state.categories.some(c=>c.name.toLowerCase()===g.toLowerCase()))await api("/api/admin/categories",{method:"POST",body:JSON.stringify({name:g})})}state.categories=await api("/api/admin/categories");const catMap=new Map(state.categories.map(c=>[c.name.toLowerCase(),c.id]));const rows=parsed.map((x,i)=>({...x,playlist_id:playlistId,category_id:catMap.get(x.group.toLowerCase()),sort_order:i+1}));for(let i=0;i<rows.length;i+=200)await api("/api/admin/channels/bulk",{method:"POST",body:JSON.stringify({channels:rows.slice(i,i+200)})});toast(`${rows.length} canales importados`);await loadAll()}catch(err){toast(err.message)}finally{e.target.value=""}};
document.querySelectorAll(".viewbtn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".viewbtn").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.view).classList.add("active");if(b.dataset.view==="reports")loadReports()});
$("btnToken").onclick=()=>$("tokenDialog").showModal();$("tokenForm").onsubmit=e=>{e.preventDefault();state.token=$("token").value.trim();sessionStorage.setItem("novaTvAdminToken",state.token);$("tokenDialog").close();loadAll()};
api("/api/health").then(()=>$("apiStatus").textContent="● API conectada").catch(()=>$("apiStatus").textContent="● API sin conexión");loadAll();
